name: Lock Inactive Issues

on:
  schedule:
    # Run at 08:00 every day
    - cron: '0 8 * * *'

jobs:
  lock_closed:
    runs-on: ubuntu-latest
    steps:
      - uses: angular/dev-infra/github-actions/lock-closed@c0073a481b41df9b94ab342842c1696b733cebaa
        with:
          lock-bot-key: ${{ secrets.LOCK_BOT_PRIVATE_KEY }}
